name: Collect news (every 30m)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install feedparser requests

      - name: Run collector
        run: |
          python collect.py
          echo "---- items.json preview ----"
          python - <<'PY'
          import json, pathlib
          d = json.loads(pathlib.Path("items.json").read_text())
          print("items:", len(d.get("items", [])))
          print("sources:", len(d.get("sources", [])))
          print("updated_at:", d.get("updated_at"))
          PY

      - name: Commit items.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add items.json
          git commit -m "Auto update items.json" || echo "No changes"
          git push