name: collect

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  push:
    paths:
      - "feeds.py"
      - ".github/workflows/collect.yml"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install feedparser python-dateutil

      - name: Collect news
        run: python feeds.py --team arizona-cardinals --limit 50

      - name: Commit items.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          git commit -m "update items.json (cards)" || echo "no changes"
          git push