name: Update Feeds

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    paths:
      - "collect.py"
      - "feeds.py"

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser==6.0.11
      - name: Run collector
        run: |
          python collect.py
          python - <<'PY'
          import json, pathlib
          d = json.loads(pathlib.Path("items.json").read_text(encoding="utf-8"))
          print("items:", len(d.get("items", [])))
          print("sources:", len(d.get("sources", [])))
          print("updated_at:", d.get("updated_at"))
PY
      - name: Commit items.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add items.json
          git commit -m "Auto update items.json" || echo "No changes"
          git push